### ISSUE TITLE
elvish swallows last line of stdout output.

### ISSUE THREAD

**Issue by hugelgupf** [u-root/u-root#1035]
elvish swallows the last line of stdout output if it doesn't end with a new-line.

E.g.

```bash
~/> echo "haha" > tmp/foo
~/> echo -n "hoho" >> tmp/foo
~/> ls -l tmp/foo
-rw-r--r-- 0 0 9 Nov 27 06:17 foo
~/> cat tmp/foo
haha
~/> 
```

**Comment by dmag** [comment]
The problem is in `cmds/core/elvish/eval/frame.go`. We read line by line, so a partial line is returned along with an EOF. Unfortunately, we don't look at the partial line when we see EOF.  The code below explicitly sends the partial `line` when we see EOF. (I'd make a PR, but it's too much work to get the tests working.)

    +++ /cmds/core/elvish/eval/frame.go
    @@ -101,6 +101,8 @@ func linesToChan(r io.Reader, ch chan<- interface{}) {
                    if err != nil {
                            if err != io.EOF {
                                    logger.Println("error on reading:", err)
    +                       } else { // We are EOF
    +                               ch <- line
                            }
                            break
                    }

Note the code above will send an empty string at the end of every "normal" file. If we care to fix, we can only send when `line` is NOT the empty string.
