### ISSUE TITLE
diskboot: BLS support

### ISSUE THREAD

**Issue by hugelgupf** [u-root/u-root#1212]
from @flammit

> noticed your updates to #1054. just wanted to note that it’s probably worth adding support / tests for parsing BLS configs now that Fedora 30 ships with it by default: https://fedoraproject.org/wiki/Changes/BootLoaderSpecByDefault

**Comment by siro20** [comment]
localboot has the same problem, starting with fedora 30 it isn't able to find the boot entries in grub.cfg

**Comment by tfg13** [comment]
There was also https://github.com/systemboot/systemboot/issues/95

I have a half-baked BLS implementation, I can try to get it somewhere in the next couple of days.

I just checked, it looks like the BLS impl in Fedora has the same issue as the RHEL8 one: One needs to parse the BLS files first, but also still parse some grub stuff, because BLS references variables defined there (mostly `$kernelopts`)

**Comment by tfg13** [comment]
Stuff is happening in #1283
