### ISSUE TITLE
Code coverage from VM tests not reporting anymore

### ISSUE THREAD

**Issue by hugelgupf** [u-root/u-root#2290]
In #2189, @MDr164 added code coverage from VM tests to codecov reports.

Compare the coverage report of blockdev_linux.go from #2189 [here](https://app.codecov.io/gh/u-root/u-root/compare/2189/tree/pkg/mount/block/blockdev_linux.go) against the coverage report of it at `main` [here](https://app.codecov.io/gh/u-root/u-root/blob/main/pkg/mount/block/blockdev_linux.go). We've lost all the coverage that was part of the VM tests.

**Comment by walterchris** [comment]
Actually it never worked. It worked in the `cover/vmtest` branch - but even within the merge commit it does not show up.

I ran these tests directly on circleci - and the issue is that even though QEMU is running the tests, the coverprofile does not reflect this. So all the lines are missing. I'm trying to understand why these do not show up when I use coverprofile within QEMU.
