### ISSUE TITLE
rm: testing suite is incomplete

### ISSUE THREAD

**Issue by ananion-cation** [u-root/u-root#327]
Many cases are not covered by rm_tests including - deleting empty directories - deleting files you do not have permission to and -deleting files that do not exist

**Comment by rminnich** [comment]
rm should not check whether you have permissions to delete a file. That permission checking is the kernel's job. That's not the same as checking about deleting a read-only file; rm is doing that check because it *IS* legal to delete a readonly file. It's actually a stupid check IMHO but who am I to argue with rm :-)

**Comment by vladimiroff** [comment]
#477 resolves this.
