### ISSUE TITLE
ping bug? read failed [...] i/o timeout

### ISSUE THREAD

**Issue by pwFoo** [u-root/u-root#642]
Maybe a bug in ping package?

Internet connection works fine (tested with `wget http://google.com` and downloaded an index.html file with content), but ping fails with a 

> read failed [...] i/o timeout

ipv4 network connection (nic module loaded, dhclient to get an valid ipv4 address).

**Comment by insomniacslk** [comment]
I believe @claudiozz and/or @tfg13 were working on fixing it

**Comment by tfg13** [comment]
Yup, we got the same error message, but on v6 (network was also working fine otherwise) @claudiozz did some initial investigation, and IIRC it pointed at something in the v6 codepath. So not sure if this is the same thing.

That being said, we will probably fix it at some point, but there is no ETA since this is not critical for us at this time.

**Comment by pwFoo** [comment]
OK, thanks. It's a low prio issue ;)

**Comment by pwFoo** [comment]
I created a initrd with alpine linux base with u-root additions and ping binary /bbin/ping works fine.

Is it solved or is the alpine rootfs the workaround?

**Comment by pwFoo** [comment]
Works fine in current u-root.
